"""make_report_tables.py -- turn the result CSVs into markdown tables for the report (exact numbers, 95% CIs).
Run from the folder that contains recommender/:   python -m recommender.make_report_tables
Reads (whatever exists): results_part2.csv, results_clean_summary.csv, sweep_lambda.csv, sweep_k.csv, results_attack.csv
Writes: recommender/report_tables.md
"""
import os
import numpy as np
import pandas as pd
from scipy import stats

D = "recommender/"


def md(df):
    cols = list(df.columns)
    lines = ["| " + " | ".join(map(str, cols)) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    return "\n".join(lines)


def pm(mean, half, nd=4):
    return f"{mean:.{nd}f} ± {half:.{nd}f}" if pd.notna(half) else f"{mean:.{nd}f}"


def clean_tables(summary):
    s = summary.set_index(["model", "metric"])
    order = list(dict.fromkeys(summary.model))
    def table(metrics, title):
        rows = []
        for m in order:
            row = {"model": m}
            for k in metrics:
                row[k] = pm(s.loc[(m, k), "mean"], s.loc[(m, k), "ci95"]) if (m, k) in s.index else "n/a"
            rows.append(row)
        n = int(summary.n.max())
        return f"### {title}\n*mean ± 95% CI half-width over {n} seeds (t distribution)*\n\n" + md(pd.DataFrame(rows))
    K = [c for c in summary.metric.unique() if c.startswith("NDCG@")][0].split("@")[1]
    return [table(["RMSE", "MAE"], "Table 1. Rating accuracy on the test split (clean data)"),
            table([f"P@{K}", f"R@{K}", f"NDCG@{K}", f"MAP@{K}"], f"Table 2. Ranking quality at K={K} (clean data)"),
            table([f"coverage@{K}", f"novelty@{K}", f"diversity@{K}"], f"Table 3. Beyond-accuracy metrics at K={K} (clean data)")]


def attack_table(att):
    keep = [c for c in ["RMSE", "NDCG@10", "prediction_shift", "hit_ratio", "mean_w_fake", "mean_w_genuine"] if c in att.columns]
    out = []
    for setting, g in att.groupby("setting", sort=False):
        rows = []
        for (model, cond), h in g.groupby(["model", "condition"], sort=False):
            n = len(h); t = stats.t.ppf(0.975, n - 1) if n > 1 else np.nan
            row = {"model": model, "condition": cond, "seeds": n}
            for c in keep:
                v = h[c].dropna().values
                if len(v):
                    sd = v.std(ddof=1) if len(v) > 1 else np.nan
                    row[c] = pm(v.mean(), t * sd / np.sqrt(len(v)) if len(v) > 1 else np.nan, 3)
            rows.append(row)
        out.append(f"#### Attack setting: {setting}\n*mean ± 95% CI half-width over seeds*\n\n" + md(pd.DataFrame(rows)))
    return out


def main():
    parts = ["# Report tables (auto-generated by make_report_tables.py)\n"]
    p = D + "results_part2.csv"
    if os.path.exists(p):
        parts.append("### Table 0. Baselines and single-run models on the validation split (seed 42)\n\n" + md(pd.read_csv(p)))
    p = D + "results_clean_summary.csv"
    if os.path.exists(p):
        parts += clean_tables(pd.read_csv(p))
    else:
        parts.append("*results_clean_summary.csv not found: run `python -m recommender.experiments clean ...`*")
    p = D + "sweep_lambda.csv"
    if os.path.exists(p):
        L = pd.read_csv(p).round(4)
        parts.append("### Table 4. Lambda sweep (k=20, validation, one seed)\n\n" + md(L))
    p = D + "sweep_k.csv"
    if os.path.exists(p):
        parts.append("### Table 5. Rank sweep with the best lambda (validation, one seed)\n\n" + md(pd.read_csv(p).round(4)))
    p = D + "results_attack.csv"
    if os.path.exists(p):
        parts.append("### Table 6. Attacked data: four conditions\n\n" + "\n\n".join(attack_table(pd.read_csv(p))))
    else:
        parts.append("*results_attack.csv not found yet (waiting for the attack data): run `python -m recommender.experiments attack ...`*")
    with open(D + "report_tables.md", "w", encoding="utf-8") as f:
        f.write("\n\n".join(parts) + "\n")
    print("wrote", D + "report_tables.md")


if __name__ == "__main__":
    main()
